In [1]:
import pandas as pd

In [2]:
file_path = "Resources/Food_Supply_kcal_Data.csv"
food_supplykcal_df = pd.read_csv(file_path)
food_supplykcal_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,4.7774,0.8504,0.0,37.1186,0.1501,0.0000,1.4757,1.2006,...,2.3012,0.7504,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.9120,16.0930,1.0591,0.0,16.2107,0.8091,0.1471,3.8982,3.8688,...,2.8244,2.7508,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0896,6.0326,0.1941,0.0,25.0112,0.4181,0.1195,3.1805,1.2543,...,5.7638,2.0457,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,1.9388,4.6927,0.2644,0.0,18.3521,0.0441,0.8372,2.3133,2.9302,...,4.2741,0.3525,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,2.3041,15.3672,1.5429,0.0,13.7215,0.2057,1.7280,3.6824,7.0356,...,4.6904,1.2960,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

In [3]:
food_supplykcal_df.describe()

,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,...,Treenuts,Vegetal Products,Vegetable Oils,Vegetables,Obesity,Confirmed,Deaths,Recovered,Active,Population
count,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,...,170.000000,170.000000,170.000000,170.000000,167.000000,164.000000,164.000000,164.000000,162.000000,1.700000e+02
mean,1.325197,9.294553,1.267419,0.002786,20.365358,0.428504,0.631501,2.011975,3.896367,2.924466,...,0.261619,40.707045,4.872421,1.086328,18.707784,2.021972,0.039370,1.452356,0.535158,4.452364e+07
std,1.062362,4.754174,1.283723,0.030879,6.467936,0.304333,0.579007,1.416149,2.216693,2.019384,...,0.285631,4.754308,2.164249,0.648232,9.633557,2.360454,0.048718,1.927617,1.329249,1.564182e+08
min,0.000000,1.623700,0.000000,0.000000,8.956500,0.018800,0.000000,0.147100,0.298000,0.116900,...,0.000000,27.708900,0.932500,0.095700,2.100000,0.000312,0.000000,0.000000,0.000000,5.400000e+04
25%,0.361300,5.082600,0.342850,0.000000,15.306175,0.141000,0.240150,1.224525,2.080700,1.107775,...,0.046625,36.830725,3.126350,0.602600,8.500000,0.140976,0.002013,0.099107,0.012028,2.816250e+06
50%,1.244600,9.034100,0.877500,0.000000,19.619950,0.403750,0.478300,1.694850,3.687450,2.719800,...,0.174000,40.969700,4.660650,1.003100,21.200000,1.011570,0.011998,0.475402,0.081040,1.018150e+07
75%,2.028050,13.174975,1.763175,0.000000,24.841450,0.632950,0.869675,2.370700,5.278325,4.319625,...,0.389575,44.940900,6.427900,1.366950,25.700000,3.487069,0.069503,2.622874,0.358183,3.271625e+07
max,5.157400,22.291100,7.800700,0.400700,37.526500,1.446100,4.418300,8.854000,10.567400,9.944100,...,1.421000,48.386400,10.383900,3.352400,45.600000,10.408199,0.185428,9.039871,8.019819,1.402385e+09

In [4]:
food_supplykcal_df.dtypes

Country                          object
Alcoholic Beverages             float64
Animal Products                 float64
Animal fats                     float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Milk - Excluding Butter         float64
Miscellaneous                   float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar Crops                     float64
Sugar & Sweeteners              float64
Treenuts                        float64
Vegetal Products                float64
Vegetable Oils                  float64
Vegetables                      float64
Obesity                         float64
Undernourished                   object
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [5]:
kcal_df = food_supplykcal_df.drop(["Undernourished","Unit (all except Population)","Confirmed", "Deaths", "Recovered","Active","Aquatic Products, Other"],axis=1)

In [6]:
kcal_df.isnull().sum()

Country                     0
Alcoholic Beverages         0
Animal Products             0
Animal fats                 0
Cereals - Excluding Beer    0
Eggs                        0
Fish, Seafood               0
Fruits - Excluding Wine     0
Meat                        0
Milk - Excluding Butter     0
Miscellaneous               0
Offals                      0
Oilcrops                    0
Pulses                      0
Spices                      0
Starchy Roots               0
Stimulants                  0
Sugar Crops                 0
Sugar & Sweeteners          0
Treenuts                    0
Vegetal Products            0
Vegetable Oils              0
Vegetables                  0
Obesity                     3
Population                  0
dtype: int64

In [7]:
kcal_df.dropna()

,Country,Alcoholic Beverages,Animal Products,Animal fats,Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,...,Starchy Roots,Stimulants,Sugar Crops,Sugar & Sweeteners,Treenuts,Vegetal Products,Vegetable Oils,Vegetables,Obesity,Population
0,Afghanistan,0.0000,4.7774,0.8504,37.1186,0.1501,0.0000,1.4757,1.2006,2.4512,...,0.3252,0.0750,0.0000,2.2261,0.1251,45.2476,2.3012,0.7504,4.5,38928000.0
1,Albania,0.9120,16.0930,1.0591,16.2107,0.8091,0.1471,3.8982,3.8688,9.9441,...,1.2651,0.2501,0.0000,3.4422,0.3972,33.9070,2.8244,2.7508,22.3,2838000.0
2,Algeria,0.0896,6.0326,0.1941,25.0112,0.4181,0.1195,3.1805,1.2543,3.9869,...,1.9262,0.1493,0.0000,3.9869,0.2240,43.9749,5.7638,2.0457,26.6,44357000.0
3,Angola,1.9388,4.6927,0.2644,18.3521,0.0441,0.8372,2.3133,2.9302,0.5067,...,12.6239,0.0441,0.0000,2.7539,0.0000,45.3184,4.2741,0.3525,6.8,32522000.0
4,Antigua and Barbuda,2.3041,15.3672,1.5429,13.7215,0.2057,1.7280,3.6824,7.0356,4.6904,...,0.8434,0.4937,0.0000,5.8218,0.0823,34.6225,4.6904,1.2960,19.1,98000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.8454,7.2303,0.6007,21.3126,0.2892,0.4449,2.3804,3.1368,2.6474,...,1.3571,0.0667,0.0000,7.7864,0.0000,42.7586,7.5417,0.6674,25.2,28645000.0
166,Vietnam,0.7150,10.9806,0.9363,26.9833,0.2894,1.0385,1.8046,7.8311,0.5618,...,0.7150,0.1021,0.1532,2.0940,0.3575,39.0364,1.3279,1.9578,2.1,96209000.0
167,Yemen,0.0000,3.4667,0.3394,32.0727,0.1455,0.1697,1.1879,2.0121,0.6545,...,0.3152,0.1212,0.0000,7.0303,0.0242,46.5455,3.9515,0.3636,14.1,29826000.0
168,Zambia,1.1925,3.3043,0.3230,31.5528,0.1988,0.5714,0.2236,1.5155,0.5217,...,4.0994,0.0248,0.0000,2.5590,0.0000,46.7081,3.0062,0.4472,6.5,18384000.0
169,Zimbabwe,1.4269,3.9356,0.6904,29.8044,0.1381,0.1611,0.4373,1.7491,1.0817,...,1.2888,0.0460,0.0000,5.0403,0.1151,46.0759,6.2601,0.2532,12.3,14863000.0

In [8]:
kcal_df.to_csv("kcal_df.csv")